permalink: /blog/:title/
relative_permalinks: false

name: Blow in the Dark Glassworks
url: http://blowinthedark.com
description: Blow in the Dark Glassworks designs and creates one of a kind, hand blown glass sculptures in Edmonton Alberta.
assetpath: /assets/dist/
bowerpath: /assets/components/

timezone: America/Edmonton

exclude:
  - .gitignore
  - .editorconfig
  - README.md
  - "*.todo"
  - Gruntfile.js
  - node_modules
  - package.json
  - bower.json
  - component.json
